# Generated by Django 5.2.8 on 2025-11-16 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_rename_projects_project'),
    ]

    operations = [
        migrations.CreateModel(
            name='Framework',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('framework_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ProgrammingLanguage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('programming_language', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='project',
            name='category',
        ),
        migrations.RemoveField(
            model_name='project',
            name='framework',
        ),
        migrations.RemoveField(
            model_name='project',
            name='programmingLanguages',
        ),
        migrations.AddField(
            model_name='project',
            name='category',
            field=models.ManyToManyField(to='projects.category'),
        ),
        migrations.AddField(
            model_name='project',
            name='framework',
            field=models.ManyToManyField(to='projects.framework'),
        ),
        migrations.AddField(
            model_name='project',
            name='programmingLanguages',
            field=models.ManyToManyField(to='projects.programminglanguage'),
        ),
    ]
