# Generated by Django 5.2.8 on 2025-11-16 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_framework_programminglanguage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='framework',
            field=models.ManyToManyField(blank=True, to='projects.framework'),
        ),
    ]
